/**
 *    Copyright ${license.git.copyrightYears} the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package com.cn.research.mybatis.generator;

public interface busDOMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table bus_info
	 *
	 * @mbg.generated
	 */
	int insert(BusDO record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table bus_info
	 *
	 * @mbg.generated
	 */
	int insertSelective(BusDO record);

	BusDO selectByPrimaryKey(Integer id);


	int updateByPrimaryKeySelective(BusDO record);

}
