/**
 *    Copyright ${license.git.copyrightYears} the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package com.cn.research.mybatis.generator;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bus_info
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class BusDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_info.bus_info_id
     *
     * @mbg.generated
     */
    private Integer busInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_info.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_info.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bus_info.bus_name
     *
     * @mbg.generated
     */
    private String busName;

    private String busId;

    public String getBusId() {
        return busId;
    }

    public void setBusId(String busId) {
        this.busId = busId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_info.bus_info_id
     *
     * @return the value of bus_info.bus_info_id
     *
     * @mbg.generated
     */
    public Integer getBusInfoId() {
        return busInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_info.bus_info_id
     *
     * @param busInfoId the value for bus_info.bus_info_id
     *
     * @mbg.generated
     */
    public void setBusInfoId(Integer busInfoId) {
        this.busInfoId = busInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_info.create_time
     *
     * @return the value of bus_info.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_info.create_time
     *
     * @param createTime the value for bus_info.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_info.modify_time
     *
     * @return the value of bus_info.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_info.modify_time
     *
     * @param modifyTime the value for bus_info.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_info.bus_name
     *
     * @return the value of bus_info.bus_name
     *
     * @mbg.generated
     */
    public String getBusName() {
        return busName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bus_info.bus_name
     *
     * @param busName the value for bus_info.bus_name
     *
     * @mbg.generated
     */
    public void setBusName(String busName) {
        this.busName = busName == null ? null : busName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bus_info.is_favour
     *
     * @return the value of bus_info.is_favour
     *
     * @mbg.generated
     */

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bus_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", busInfoId=").append(busInfoId);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", busName=").append(busName);
        sb.append("]");
        return sb.toString();
    }
}